"use strict";

require("dotenv").config();

const Razorpay = require("razorpay");
const pointsRedemption = require("./referral/commands/points_redemption");

const INTERNATIONAL_MARKUP_PERCENT = 50; // Change to adjust markup for all intl users

// Currencies accepted by Razorpay for Indian merchants in international mode.
// Any currency NOT in this set is silently replaced with USD so the order
// creation never fails due to an unsupported currency code.
const RAZORPAY_SUPPORTED_INTL = new Set([
    'usd','gbp','eur','sgd','aed','aud','cad','chf',
    'hkd','jpy','myr','nzd','nok','sek','dkk','zar',
    'qar','sar','thb','mxn',
]);

const CURRENCY_SYMBOLS = {
    'USD': '$',   'GBP': '£',   'EUR': '€',   'SGD': 'S$',
    'AED': 'د.إ', 'AUD': 'A$',  'CAD': 'C$',  'CHF': 'CHF',
    'HKD': 'HK$', 'JPY': '¥',   'MYR': 'RM',  'NZD': 'NZ$',
    'NOK': 'kr',  'SEK': 'kr',  'DKK': 'kr',  'ZAR': 'R',
    'QAR': '﷼',   'SAR': '﷼',   'THB': '฿',   'MXN': 'Mex$',
};

// Returns the Razorpay-safe currency code: falls back to USD if not supported.
function resolveIntlCurrency(currencyCode) {
    const code = currencyCode.toUpperCase();
    return RAZORPAY_SUPPORTED_INTL.has(code.toLowerCase()) ? code : 'USD';
}

// Currencies where Razorpay expects the amount with no decimal multiplier
const ZERO_DECIMAL_CURRENCIES = new Set([
    'bif','clp','djf','gnf','jpy','kmf','krw','mga','pyg','rwf',
    'ugx','vnd','vuv','xaf','xof','xpf',
]);

// Currencies where Razorpay expects amounts in 1/1000 units
const THREE_DECIMAL_CURRENCIES = new Set(['bhd','jod','kwd','omr','tnd']);

// In-memory rate cache: { rates: {...}, fetchedAt: timestamp }
let _ratesCache = null;

async function fetchExchangeRates() {
    const SIX_HOURS = 6 * 60 * 60 * 1000;
    if (_ratesCache && Date.now() - _ratesCache.fetchedAt < SIX_HOURS) {
        return _ratesCache.rates;
    }
    const res = await fetch(
        'https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/inr.json'
    );
    const json = await res.json();
    _ratesCache = { rates: json.inr, fetchedAt: Date.now() };
    return _ratesCache.rates;
}

function getDecimalPlaces(currencyCode) {
    const code = currencyCode.toLowerCase();
    if (ZERO_DECIMAL_CURRENCIES.has(code)) return 0;
    if (THREE_DECIMAL_CURRENCIES.has(code)) return 3;
    return 2;
}

function convertInrToIntl(inrAmount, targetCurrencyCode, rates) {
    const code = targetCurrencyCode.toLowerCase();
    const rate = rates[code];
    if (!rate) throw new Error(`No exchange rate for ${targetCurrencyCode}`);
    const raw = inrAmount * rate;
    const withMarkup = raw * (1 + INTERNATIONAL_MARKUP_PERCENT / 100);
    const decimals = getDecimalPlaces(targetCurrencyCode);
    const multiplier = Math.pow(10, decimals);
    const display = decimals === 0
        ? String(Math.round(withMarkup))
        : (Math.round(withMarkup * 100) / 100).toFixed(2);
    const amount = Math.round(withMarkup * multiplier);
    return { display, amount };
}

// No-coupon INR base price per premium package. Points only ever apply when NO
// coupon is present (coupon XOR points), so the no-coupon base is always correct
// here. KEEP IN SYNC with the premium amounts in getPrice() below.
const PREMIUM_BASE_INR = {
    tbd_traveler_one_week_plus1: 99,
    tbd_traveler_one_month: 499,
    tbd_traveler_one_year: 999,
    tbd_elite: 2999,
};

// Returns the INR base price (rupees) that wallet points should be applied to.
// Premium: from the table (price is set server-side from packageId). Flights /
// hotels: they pass selPrice in INR paise, so the base is selPrice/100.
function resolveBaseInr(data) {
    if (data.source === "premium") {
        return PREMIUM_BASE_INR[data.packageId] || 0;
    }
    if (data.source === "tboFlights" || data.source === "tboHotels") {
        return Math.round(Number(data.selPrice) / 100) || 0;
    }
    return 0;
}

/*
    name: getOrderId
    description: returns the order id which is generated by Razor pay
    param: selPrice (int)
*/
exports.getOrderId = async function (data) {
    var instance = new Razorpay({
        key_id: process.env.RAZORPAY_KEY,
        key_secret: process.env.RAZORPAY_SECRET_KEY,
    });
    await getPrice(data);
    var extraInfo = data.extraInfo ? data.extraInfo : {};

    // --- Wallet points redemption (server-authoritative) -------------------
    // When the client opts in (usePoints), reserve the eligible points and shave
    // the discount off selPrice BEFORE the order is created. The hold is settled
    // on payment.captured (webhook) or released if the order fails/abandons.
    // Guarded to INR + eligible sources; the wallet user comes from the JWT
    // (data.plainUserId), never the client-supplied userId.
    let pointsHold = null;
    const walletUserId = Number(data.plainUserId || data.walletUserId || 0);
    const orderCurrency = String(data.currencyCode || data.currency || "INR").toUpperCase();
    // Coupon XOR points: never stack a coupon discount with wallet points.
    // Premium passes the code in couponApplied; flights/hotels apply it in their
    // builder and surface it via extraInfo.couponCode.
    const hasCoupon =
        (typeof data.couponApplied === "string" && data.couponApplied.trim() !== "") ||
        !!(data.extraInfo && data.extraInfo.couponCode);
    // Points are ₹-denominated. They are applied to the INR BASE price first,
    // then (for non-INR orders) the discounted base is converted with the same
    // markup the price used — so 10 pts = a genuine ₹10 off in any currency.
    const baseInr = resolveBaseInr(data);
    const redeemEligible =
        !!data.usePoints &&
        !hasCoupon &&
        walletUserId > 0 &&
        baseInr > 0 &&
        pointsRedemption.isEligibleSource(data.source);
    // Always log the redemption decision so a "discount not applied" report is
    // immediately diagnosable from server logs.
    console.log("[points] getOrderId redemption check", {
        usePoints: data.usePoints,
        hasCoupon,
        walletUserId,
        currency: orderCurrency,
        source: data.source,
        baseInr,
        selPriceBefore: data.selPrice,
        eligible: redeemEligible,
    });
    if (redeemEligible) {
        try {
            const reserved = await pointsRedemption.reservePoints({
                userId: walletUserId,
                payableRupees: baseInr,
                source: data.source,
            });
            console.log("[points] reservePoints result", { baseInr, reserved });
            if (reserved && reserved.points > 0) {
                pointsHold = reserved;
                const netInr = baseInr - reserved.discountRupees;
                if (orderCurrency === "INR") {
                    data.selPrice = netInr * 100;
                } else {
                    // Re-derive the foreign amount from the discounted INR base.
                    const rates = await fetchExchangeRates();
                    data.selPrice = convertInrToIntl(netInr, orderCurrency, rates).amount;
                }
                extraInfo = {
                    ...extraInfo,
                    pointsRedeemed: reserved.points,
                    pointsDiscountRupees: reserved.discountRupees,
                };
                console.log("[points] discount applied", {
                    discountRupees: reserved.discountRupees,
                    netInr,
                    selPriceAfter: data.selPrice,
                });
            } else {
                console.log("[points] no points reserved (balance 0 or below cap); full price");
            }
        } catch (e) {
            console.error("[points] reservation failed; proceeding at full price", e);
            pointsHold = null;
        }
    }

    let resp;
    try {
        resp = await instance.orders.create({
            amount: data.selPrice,
            currency: data.currencyCode,
            receipt: "receipt#1",
            notes: {
                userId: data.userId,
                packageId: data.packageId,
                couponApplied: data.couponApplied,
                source: data.source,
                pointsRedeemed: pointsHold ? pointsHold.points : 0,
                extraInfo: extraInfo
            },
        });
    } catch (orderErr) {
        // Order never got created — give the reserved points straight back.
        if (pointsHold) {
            await pointsRedemption.releaseHold({ holdId: pointsHold.holdId, reason: "booking_redeem_order_failed" });
        }
        throw orderErr;
    }

    if (pointsHold) {
        try {
            await pointsRedemption.attachOrderId(pointsHold.holdId, resp.id);
        } catch (e) {
            // Can't link the hold to the order → release so points aren't stuck debited.
            console.error("attachOrderId failed; releasing hold", e);
            await pointsRedemption.releaseHold({ holdId: pointsHold.holdId, reason: "booking_redeem_attach_failed" });
        }
    }

    console.log(resp);
    return resp;
};

/*
    name: getPrice
    description: To make the amount tamper proof, we are setting the values
    param: data (Object)
*/
async function getPrice(data) {
    if (data.source == 'premium') {
        if (data.packageId == 'tbd_traveler_one_week_plus1') {
            if (data.currencyCode == 'INR') {
                data.selPrice = 99 * 100;
            } else {
                const resolved = resolveIntlCurrency(data.currencyCode);
                data.currencyCode = resolved; // update so order is created in safe currency
                const rates = await fetchExchangeRates();
                const { amount } = convertInrToIntl(99, resolved, rates);
                data.selPrice = amount;
            }
        } else if (data.packageId == 'tbd_traveler_one_month') {
            if (data.currencyCode == 'INR') {
                data.selPrice = 499 * 100;
            } else {
                const resolved = resolveIntlCurrency(data.currencyCode);
                data.currencyCode = resolved;
                const rates = await fetchExchangeRates();
                const { amount } = convertInrToIntl(499, resolved, rates);
                data.selPrice = amount;
            }
        } else if (data.packageId == 'tbd_traveler_one_year') {
            if (data.currencyCode == 'INR') {
                if (data.couponApplied == 'BUDDY100') {
                    data.selPrice = 899 * 100;
                } else if (data.couponApplied == 'LUV200') {
                    data.selPrice = 799 * 100;
                } else {
                    data.selPrice = 999 * 100;
                }
            } else {
                const resolved = resolveIntlCurrency(data.currencyCode);
                data.currencyCode = resolved;
                let inrBase;
                if (data.couponApplied == 'BUDDY100') {
                    inrBase = 899;
                } else if (data.couponApplied == 'BUDDY200' || data.couponApplied == 'LUV200') {
                    inrBase = 799;
                } else {
                    inrBase = 999;
                }
                const rates = await fetchExchangeRates();
                const { amount } = convertInrToIntl(inrBase, resolved, rates);
                data.selPrice = amount;
            }
        } else if (data.packageId == 'tbd_elite') {
            if (data.currencyCode == 'INR') {
                if (data.couponApplied == 'BUDDY100') {
                    data.selPrice = 2899 * 100;
                } else if (data.couponApplied == 'LUV200') {
                    data.selPrice = 2799 * 100;
                } else if (data.couponApplied == 'SPECIAL500') {
                    data.selPrice = 2499 * 100;
                } else {
                    data.selPrice = 2999 * 100;
                }
            } else {
                const resolved = resolveIntlCurrency(data.currencyCode);
                data.currencyCode = resolved;
                let inrBase;
                if (data.couponApplied == 'BUDDY100') {
                    inrBase = 2899;
                } else if (data.couponApplied == 'BUDDY200' || data.couponApplied == 'LUV200') {
                    inrBase = 2799;
                } else if (data.couponApplied == 'SPECIAL500') {
                    inrBase = 2499;
                } else {
                    inrBase = 2999;
                }
                const rates = await fetchExchangeRates();
                const { amount } = convertInrToIntl(inrBase, resolved, rates);
                data.selPrice = amount;
            }
        }
    }
    if (['mobileAiPremium', 'webAiPremium'].indexOf(data.source) >= 0) {
        if (data.packageId == 'tbd_ai_mini') {
            data.selPrice = 9 * 100;
        } else if (data.packageId == 'tbd_ai_super') {
            data.selPrice = 39 * 100;
        }
    }
}

// INR base prices used by getPlanPrices
const _INR_BASE = {
    month:           499,
    yearBase:        999,
    yearBuddy100:    899,
    yearBuddy200:    799,
    eliteBase:      2999,
    eliteBuddy100:  2899,
    eliteBuddy200:  2799,
    eliteSpecial500: 2499,
};

/*
    name: getPlanPrices
    description: Returns display + payment amounts for all plan/coupon combos
                 in the requested currency. INR values are hardcoded; all others
                 are dynamically converted with a markup from live exchange rates.
    param: currencyCode (string)
*/
exports.getPlanPrices = async function (currencyCode) {
    const code = (currencyCode || 'INR').toUpperCase();
    if (code === 'INR') {
        const prices = {};
        for (const [key, inr] of Object.entries(_INR_BASE)) {
            prices[key] = { display: String(inr), amount: inr * 100 };
        }
        return { prices, resolvedCurrency: 'INR', resolvedSymbol: '₹' };
    }

    const resolved = resolveIntlCurrency(code);
    const symbol = CURRENCY_SYMBOLS[resolved] || '$';
    const rates = await fetchExchangeRates();
    const prices = {};
    for (const [key, inr] of Object.entries(_INR_BASE)) {
        prices[key] = convertInrToIntl(inr, resolved, rates);
    }
    return { prices, resolvedCurrency: resolved, resolvedSymbol: symbol };
};

/*
    name: getPaymentDetails
    description: To get payment details of the passed paymentId paramenter
    param: paymentId (string)
*/
exports.getPaymentDetails = async function (paymentId) {
    console.log('PaymentId:', paymentId);
    var instance = new Razorpay({
        key_id: "rzp_live_BjxKA67DtRqxta",
        key_secret: "bB4J3IpRinm2czZ0zNfi0IAs",
    });

    var resp = instance.payments.fetch(paymentId);
    console.log(resp);
    return resp;
};


/*
    name: getPaymentDetails
    description: To get payment details of the passed paymentId paramenter
    param: paymentId (string)
*/
exports.initiateRefund = async function (paymentId, refundAmount, reason) {
    let refund;
    try {
        var razorPayInstance = new Razorpay({
            key_id: process.env.RAZORPAY_KEY,
            key_secret: process.env.RAZORPAY_SECRET_KEY
        });

        refund = await razorPayInstance.payments.refund(paymentId, {
          amount: refundAmount * 100, // amount in paise (multiply by 100)
          notes: {
            note_key: reason ? reason : "Requested for refund"
          }
        });
        console.log('Refund Initiated:', refund);
    } catch (error) {
        console.error('Error initiating refund:', error);
    }
    return refund;
};

exports.validatePayment = async function (data){
    let paymentId = data.paymentId;
    let orderId = data.orderId;
    let userId = data.userId;
    console.log('Validating PaymentId', paymentId);
    var instance = new Razorpay({
        key_id: process.env.RAZORPAY_KEY,
        key_secret: process.env.RAZORPAY_SECRET_KEY,
    });
    let isValidPayment = true;
    let paymentDetails;
    try {
        paymentDetails = await instance.payments.fetch(paymentId);
    } catch (error) {
        console.log('Error:', error.message);
    }
    if (!paymentDetails){
        return false;
    }
    if (paymentDetails.statusCode == 400){
        return false;
    }
    if (paymentDetails.order_id != orderId){
        isValidPayment = false;
    }
    if (isValidPayment && paymentDetails.notes.extraInfo){
        if (data.traceId != paymentDetails.notes.extraInfo.traceId){
            isValidPayment = false;
        }
    }
    return isValidPayment;
}

/*
    name: getPaymentsByOrderId
    description: Fetch all payments associated with an orderId from Razorpay
    param: orderId (string)
*/
exports.getPaymentsByOrderId = async function (orderId) {
    console.log('Fetching payments for OrderId:', orderId);
    var instance = new Razorpay({
        key_id: process.env.RAZORPAY_KEY,
        key_secret: process.env.RAZORPAY_SECRET_KEY,
    });

    try {
        // Fetch all payments for this order
        const payments = await instance.orders.fetchPayments(orderId);
        console.log('Payments fetched:', payments);
        return payments;
    } catch (error) {
        console.log('Error fetching payments by orderId:', error.message);
        throw error;
    }
};

const crypto = require('crypto');

/**
 * Verify Razorpay webhook signature (raw JSON body).
 * Prefer RAZORPAY_WEBHOOK_SECRET from Dashboard → Webhooks; fall back to API secret.
 */
exports.verifyWebhookSignature = function (rawBodyBuffer, signatureHeader) {
    const envSecret =
        process.env.RAZORPAY_WEBHOOK_SECRET || process.env.RAZORPAY_SECRET_KEY;
    const secret = String(envSecret || '')
        .trim()
        .replace(/^"(.*)"$/, '$1');
    const signature = String(signatureHeader || '')
        .trim()
        .toLowerCase();
    if (!secret || !signature || !rawBodyBuffer) {
        return false;
    }
    const body =
        Buffer.isBuffer(rawBodyBuffer)
            ? rawBodyBuffer
            : Buffer.from(String(rawBodyBuffer), 'utf8');
    const expected = crypto
        .createHmac('sha256', secret)
        .update(body)
        .digest('hex')
		.toLowerCase();
	console.log('expected', expected);
	console.log('signature', signature);
    try {
        if (
            expected.length === 64 &&
            signature.length === 64 &&
            /^[0-9a-f]+$/.test(expected) &&
            /^[0-9a-f]+$/.test(signature)
        ) {
            return crypto.timingSafeEqual(
                Buffer.from(expected, 'hex'),
                Buffer.from(signature, 'hex'),
            );
        }
        return crypto.timingSafeEqual(
            Buffer.from(expected, 'utf8'),
            Buffer.from(signature, 'utf8'),
        );
    } catch (e) {
        return false;
    }
};
